blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogCreatView, BlogDetailView, BlogUpdateView, BlogDeleteView, published_func, \
    FullListView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='start_list'),
    path('create/', BlogCreatView.as_view(), name='create'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('full_list/', FullListView.as_view(), name='full_list'),
    path('publishing/<int:pk>', published_func, name='published_func')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from catalog.views import catalog, home

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('home/', include('catalog.urls')),
                  path('', include('catalog.urls')),
                  path('login/', include('users.urls')),
                  path('dogs/', include('dogs.urls', namespace='dogs')),
                  path('lesson20_2/', include('lesson_20_2.urls')),
                  path('main/', include('main.urls', namespace='main')),
                  path('materials/', include('materials.urls', namespace='materials')),
                  path('blog/', include('blog.urls', namespace='blog'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path

from dogs.apps import DogsConfig
from dogs.views import   Breeds, DogsListView, DogCreateView, DogUpdateView, DogDeleteView, IndexView
#index,

app_name = DogsConfig.name

urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('breeds/', Breeds.as_view(), name='breeds'),
    path('<int:pk>/dogs/', DogsListView.as_view(), name='dogs_list'),
    path('create/', DogCreateView.as_view(), name='dog_create'),
    path('<int:pk>/edit/', DogUpdateView.as_view(), name='dog_update'),
    path('<int:pk>/delete/', DogDeleteView.as_view(), name='dog_delete')

]

dogs/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Breed(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    destcription = models.CharField(max_length=500, verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'


class Dog(models.Model):
    name = models.CharField(max_length=100, verbose_name='Кличка')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='Порода')
    # breed = models.CharField(max_length=100, verbose_name='Порода')
    photo = models.ImageField(upload_to='photo/', verbose_name='Аватар', **NULLABLE)
    birth_day = models.DateField(**NULLABLE, verbose_name='Дата рождения')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Порода'
        verbose_name_plural = 'Породы'


class Parent(models.Model):
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE, verbose_name='Собака')
    name = models.CharField(max_length=150, verbose_name='Кличка')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='Порода')
    birth_day = models.DateField(verbose_name='Дата рождения', **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.breed}'

    class Meta:
        verbose_name = 'Предок'
        verbose_name_plural = 'Предки'

dogs/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render, reverse

from dogs.froms import DogForm, ParentForm
from dogs.models import Dog, Breed, Parent
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse_lazy

"""def index(request):
    dogs_list = Dog.objects.all()[:3]
    context = {
        "object_list": dogs_list,
        "title": 'Питомник - Главная'
    }
    return render(request, 'dogs/index.html', context)
"""


class IndexView(TemplateView):
    template_name = 'dogs/index.html'
    extra_context = {

        "title": 'Питомник - Главная'
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Breed.objects.all()[:3]
        return context_data


"""def breeds(request):
    dogs_list = Dog.objects.all()
    context = {
        "object_list": dogs_list,
        "title": 'Все наши породы'
    }
    return render(request, 'dogs/breeds.html', context)
"""


class Breeds(ListView):
    model = Breed
    template_name = 'dogs/breeds.html'
    extra_context = context = {

        "title": 'Все наши породы'
    }


'''def breeds_dogs(request, pk):
    breed_item = Breed.objects.get(pk=pk)
    context = {
        "object_list": Dog.objects.filter(breed_id=pk),
        "title": f'Собаки породы {breed_item.name}'
    }
    return render(request, 'dogs/dogs.html', context)
    '''


class DogsListView(ListView):
    model = Dog
    template_name = 'dogs/dogs.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(breed_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        breed_item = Breed.objects.get(pk=self.kwargs.get('pk'))
        context_data['breed_id'] = breed_item.pk,
        context_data['title'] = f'Собаки породы {breed_item.name}'

        return context_data


class DogCreateView(CreateView):
    model = Dog

    form_class = DogForm
    success_url = reverse_lazy('dogs:breeds')


class DogUpdateView(UpdateView):
    model = Dog

    form_class = DogForm

    def get_success_url(self):
        return  reverse('dogs:dog_update',  args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        ParentFormset = inlineformset_factory(Dog, Parent, form=ParentForm, extra=1)
        if self.request.method == 'POST':
            formset = ParentFormset(self.request.POST, instance=self.object)
        else:
            formset = ParentFormset(instance=self.object)

        context_data['formset'] = formset
        # with open('file', 'wt', encoding='UTF-8') as file:
        #    file.write(str(context_data))
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        # with open('file.txt', 'wt', encoding='UTF-8')as file:
        #    file.write(str(context_data))
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class DogDeleteView(DeleteView):
    model = Dog
    success_url = reverse_lazy('dogs:breeds')

dogs/templates/dogs/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{{title}}</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">Питомник</h4>

                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'dogs:breeds' %}" class="text-white">Породы</a></li>
                        <li><a href="{% url 'dogs:index' %}" class="text-white">Главная</a></li>


                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Album</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{title}}</h1>

        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}

        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

<script src="{% static  'js/popper.min.js' %}"></script>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

dogs/templates/dogs/breed_detail.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}


    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top"

                         src="{{ object.photo | mymedia }}" alt="Нет картинки">

                    {# src="/media/{{ object.photo }}" #}
                    <div class="card-body">
                        <p class="card-text">{{ object.name | title }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
{% endblock %}

dogs/templates/dogs/breeds.html
{% extends 'dogs/base.html' %}
{% block content %}

    <div class="row">
    <div class="col-12 mb-5" >

        <a href="{% url 'dogs:dog_create' %}" class="btn btn-primary">Создать собаку</a>
    </div>
        {% for object in object_list %}
            {% include 'dogs/includes/inc_breed.html' %}

        {% endfor %}
{% endblock %}

dogs/templates/dogs/dog_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">

                    <div class="card-header">
                        Удаление собаки

                    </div>

                    <form method="post">
                        {% csrf_token %}
                        <p>Действительно удаляем {{ object.name }}?</p>
                        <div class="card-body">
                            <button type="submit" class="btn  btn-outline-danger">
                                Удаляем?
                            </button>
                        <a href="{% url 'dogs:breeds' %}" class="btn btn-link" type="submit">Отмена</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dogs/templates/dogs/dog_form.html
{% extends 'main/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col-12">

            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <div class="card-header">
                            {% if object %}
                                Редактирование собаки
                            {% else %}
                                Добавление собаки
                            {% endif %}

                        </div>


                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Родословная
                </div>
                <div class="card-body">

                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                        {% if not forloop.last%}
                            <hr>
                        {% endif %}
                    {% endfor %}


                </div>
            </div>
        </div>

    </form>
{% endblock %}

dogs/templates/dogs/dog_from.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                    <div class="card-header">
                        {% if object %}
                        Редактирование собаки
                        {% else %}
                        Добавление собаки
                        {% endif %}

                    </div>

                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

dogs/templates/dogs/dogs.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}


    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top"

                         src="{{ object.photo | mymedia }}" alt="Нет картинки">

                    {# src="/media/{{ object.photo }}" #}
                    <div class="card-body">
                        <p class="card-text">{{ object.name | title }}</p>
                        <span class="text-muted">{{ object.birth_day }}</span>
                        <div class="d-flex justify-content-between align-items-center">

                            <div class="btn-group">
                            <a class="btn btn-link" href="{% url 'dogs:dog_update' object.pk %}">Редактировать</a>
                            <a class="btn btn-link" href="{% url 'dogs:dog_delete' object.pk %}">Удалить</a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            </div>
        {% endfor %}
{% endblock %}

dogs/templates/dogs/index.html
{% extends 'dogs/base.html' %}
{% block content %}

    <div class="row">
        {% for object in object_list %}
            {% include 'dogs/includes/inc_breed.html' with object=object %}
        {% endfor %}
{% endblock %}

dogs/templates/dogs/нерабочая_форма.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">

                    <div class="card-header">
                        Удаление собаки

                    </div>

                    <form method="post">
                        {% csrf_token %}
                        <p>Действительно удаляем {{ object.name }}?</p>
                        <div class="card-body">
                            <button type="submit" class="btn  btn-outline-danger">
                                Удаляем?
                            </button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}