blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogCreatView, BlogDetailView, BlogUpdateView, BlogDeleteView, published_func, \
    FullListView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='start_list'),
    path('create/', BlogCreatView.as_view(), name='create'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('full_list/', FullListView.as_view(), name='full_list'),
    path('publishing/<int:pk>', published_func, name='published_func')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from catalog.views import catalog, home

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('home/', include('catalog.urls')),
                  path('', include('catalog.urls')),
                  path('login/', include('users.urls')),
                  path('dogs/', include('dogs.urls', namespace='dogs')),
                  path('lesson20_2/', include('lesson_20_2.urls')),
                  path('main/', include('main.urls', namespace='main')),
                  path('materials/', include('materials.urls', namespace='materials')),
                  path('blog/', include('blog.urls', namespace='blog'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path

from dogs.apps import DogsConfig
from dogs.views import   Breeds, DogsListView, DogCreateView, DogUpdateView, DogDeleteView, IndexView
#index,

app_name = DogsConfig.name

urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('breeds/', Breeds.as_view(), name='breeds'),
    path('<int:pk>/dogs/', DogsListView.as_view(), name='dogs_list'),
    path('create/', DogCreateView.as_view(), name='dog_create'),
    path('<int:pk>/edit/', DogUpdateView.as_view(), name='dog_update'),
    path('<int:pk>/delete/', DogDeleteView.as_view(), name='dog_delete')

]

materials/urls.py
from django.urls import path

from materials.views import MaterialCreateView, MaterialListView, MaterialDetailView, MaterialUpdateView, \
    MaterialDeleteView
from materials.apps import MaterialsConfig

app_name = MaterialsConfig.name

urlpatterns = [

    path('create/', MaterialCreateView.as_view(), name='create'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', MaterialUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MaterialDeleteView.as_view(), name='delete'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, ProfileView

app_name = 'users'


urlpatterns =[
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile')

]

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    heading = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=150, verbose_name='slug')
    content = models.TextField(verbose_name='Содержимое', **NULLABLE)
    preview = models.ImageField(upload_to='blog/', verbose_name='Изображение', **NULLABLE)
    date_of_create = models.DateField(verbose_name='Дата создания', **NULLABLE)
    is_published = models.BooleanField(verbose_name='Опубликовано', default=True)
    count_of_views = models.IntegerField(verbose_name='Количество просмотров', default=0)



    def __str__(self):
        return f'{self.heading} {self.date_of_create}'

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"
        ordering = ('date_of_create',)


class Version(models.Model):
    product = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name='Наименование')
    numbers = models.CharField(max_length=150, verbose_name='Номер Версии')
    versions_name = models.CharField(max_length=150, verbose_name='Название версии')
    is_active = models.BooleanField(verbose_name='признак версии', **NULLABLE)

    #def __str__(self):
    #   return {self.versions_name}

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

blog/forms.py
from django import forms
from blog.models import Blog, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class BlogForm(StyleFormMixin, forms.ModelForm):
    wrong_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

    class Meta:
        model = Blog
        fields = ('heading', 'content', 'preview')

    def clean_heading(self):
        cleaned_data = self.cleaned_data.get('heading')

        if cleaned_data.lower() in self.wrong_words:
            raise forms.ValidationError('В заголовке есть недопустимое слово')
        return cleaned_data

    def clean_content(self):
        cleaned_data = self.cleaned_data.get('content')

        if cleaned_data.lower() in self.wrong_words:
            raise forms.ValidationError('В описании есть недопустимое слово')
        return cleaned_data


class VersionFrom(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

blog/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render
from datetime import date
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
# , TemplateView оставил для других проектов
from pytils.translit import slugify
from django.urls import reverse_lazy, reverse
from blog.models import Blog, Version
from django.shortcuts import get_object_or_404, redirect
from blog.forms import BlogForm, VersionFrom


class BlogCreatView(CreateView):
    model = Blog
    form_class = BlogForm

    success_url = reverse_lazy('blog:start_list')
    extra_context = {

        "title": 'Создание публикации'
    }

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.heading)
            new_blog.date_of_create = date.today()
            new_blog.save()

        return super().form_valid(form)


def published_func(request, pk):
    student_item = get_object_or_404(Blog, pk=pk)
    if student_item.is_published:
        student_item.is_published = False

    else:
        student_item.is_published = True

    student_item.save()

    return redirect(reverse('blog:full_list'))


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_of_views += 1
        self.object.save(update_fields=['count_of_views'])
        return self.object


class BlogListView(ListView):
    model = Blog



    def get_queryset(self):
        queryset = super().get_queryset()
        active_versions = Version.objects.filter(is_active=True).select_related('product')
        active_products = {version.product_id: version for version in active_versions}
        for product in queryset:
            product.active_version = active_products.get(product.id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = self.get_queryset()
        context['products'] = queryset
        return context



class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        BlogFormset = inlineformset_factory(Blog, Version, form=VersionFrom, extra=1)
        if self.request.method == 'POST':
            formset = BlogFormset(self.request.POST, instance=self.object)
        else:
            formset = BlogFormset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        # with open('file.txt', 'wt', encoding='UTF-8')as file:
        #    file.write(str(context_data))
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:start_list')


class FullListView(ListView):
    model = Blog
    template_name = 'blog/blog_full_list.html'

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>

    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "main:index" %}">Студенты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "dogs:index" %}">Питомник</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "materials:list" %}">Материалы</a>

        <a class="p-2 btn btn-outline-primary" href="{% url "blog:start_list" %}">Блог</a>

        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url "users:logout" %}">Выйти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "users:profile" %}">Профиль</a>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url "users:login" %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "users:register" %}">Регистрация</a>
        {% endif %}


    </nav>

</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
{% block content %}
{% endblock %}




    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить материал {{ object.title }}?</p>
                            <button type="submit" class="btn btn-success">Подтвердить</button>
                            <a href="{% url 'materials:list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.ht__' %}
{% load blog_tags %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {{ object.heading }}
                        </h3>
                        <h4 class="text-capitalize">
                        {{ object.slug }}
                        </h4>
                        <div>
                            <img src="{{ object.preview | mymedia }}" width="200" alt="Нет картинки">
                            <!--<img src="/media/blog/{{ object.preview }}">-->

                    </div>

                    <div class="card-body">
                        <p>
                            {{ object.content }}
                        </p>
                    </div>
                    <div class="card-footer">
                        Просмотры {{ object.count_of_views }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <form method="post">
        <div class="col-12">

            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <div class="card-header">
                            {% if object %}
                                Редактирование публикации
                            {% else %}
                                Добавление публикации
                            {% endif %}

                        </div>


                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>

                    </div>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <div class="card-header">
                            Версия
                        </div>


                        {{ formset.management_form }}
                        {% for form in formset %}
                            {{ form.as_p }}
                            {% if forloop.revcounter != 0 %}
                                <hr>
                            {% endif %}
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

blog/templates/blog/blog_full_list.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Создать публикацию</a>
    </div>
    {% for object in object_list %}

        <div class="col-md-4">
            <div class="card mb-4 box-shadow">

                <div class="card-body">
                    <p class="card-text">

                        {{ object|title }}</p>


                    <div class="d-flex justify-content-between align-items-center">
                        <a href="{% url 'blog:view' object.pk %}">View</a>
                        <a href="{% url 'blog:edit' object.pk %}">Edit</a>
                        <a href="{% url 'blog:delete' object.pk %}">Delete</a>

                        {% if object.is_published %}
                            <a href="{% url 'blog:published_func' object.pk %}" type="button"
                               class="btn btn-sm btn-warning">Скрыть</a>
                        {% else %}
                            <a href="{% url 'blog:published_func' object.pk %}" type="button"
                               class="btn btn-sm btn-success">Опубликовать</a>
                        {% endif %}


                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% load blog_tags %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Создать публикацию</a>
    </div>
    {% for object in object_list %}

        <div class="col-md-4">
            <div class="card mb-4 box-shadow">

                <div class="card-body">
                    <p class="card-text">
                            {% if user.is_authenticated %}
                            {{ object.active_version.version_name }}
                            {{ object|title }}
                            </p>
                            <P class="card-img">
                            <img src="{{ object.preview | mymedia }}" width="200" alt="Нет картинки">

                            </P>
                            <p>
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% endfor %}
                            </p>
                            {% endif %}

                    <div class="d-flex justify-content-between align-items-center">
                        <a href="{% url 'blog:view' object.pk %}">View</a>
                        <a href="{% url 'blog:edit' object.pk %}">Edit</a>
                        <a href="{% url 'blog:delete' object.pk %}">Delete</a>



                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}