blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogCreatView, BlogDetailView, BlogUpdateView, BlogDeleteView, published_func, \
    FullListView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='start_list'),
    path('create/', BlogCreatView.as_view(), name='create'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('full_list/', FullListView.as_view(), name='full_list'),
    path('publishing/<int:pk>', published_func, name='published_func')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from catalog.views import catalog, home

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('home/', include('catalog.urls')),
                  path('', include('catalog.urls')),
                  path('login/', include('users.urls')),
                  path('dogs/', include('dogs.urls', namespace='dogs')),
                  path('lesson20_2/', include('lesson_20_2.urls')),
                  path('main/', include('main.urls', namespace='main')),
                  path('materials/', include('materials.urls', namespace='materials')),
                  path('blog/', include('blog.urls', namespace='blog'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.views import StudentListView, contact, StudentDetailView, StudentCreateView, StudentUpdateView, \
    StudentDeleteView, toggle_activity

from main.apps import MainConfig

app_name = MainConfig.name

urlpatterns = [

    path('', StudentListView.as_view(), name='index'),
    path('contact/', contact, name='contact'),
    path('<int:pk>/view/', StudentDetailView.as_view(), name='view_student'),
    path('create/', StudentCreateView.as_view(), name='create_student'),
    path('<int:pk>/edit/', StudentUpdateView.as_view(), name='update_student'),
    path('<int:pk>/delete/', StudentDeleteView.as_view(), name='delete_student'),
    path('<int:pk>/activity/', toggle_activity, name='toggle_activity'),


]

main/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Student(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    avatar = models.ImageField(upload_to='students/', verbose_name='аватар', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name="Учится")
    email = models.CharField(max_length=150, verbose_name='email' ,unique=True, **NULLABLE)
    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = "Студент"
        verbose_name_plural = "Студенты"
        ordering = ('last_name',)


class Subject(models.Model):
    title = models.CharField(max_length=150, verbose_name='Название')
    description = models.TextField(verbose_name='Описание' )

    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='Студент')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Предмет'
        verbose_name_plural = 'Предметы'

main/forms.py
from django import forms
from main.models import Student, Subject


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class StudentFrom(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Student
        # fields = '__all__'  если нужно все поля указать
        fields = ('first_name', 'last_name', 'avatar', 'email')
        # exclude = ('is_active,)если нужно исключить поле(поля)

    def clean_email(self):
        cleaned_data = self.cleaned_data['email']

        if 'sky.pro' not in cleaned_data:
            raise forms.ValidationError('Почта должна относиться к учебному заведению')

        return cleaned_data


class SubjectForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Subject
        fields = '__all__'

    '''def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
    '''

main/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect
from main.models import Student, Subject
from django.shortcuts import get_list_or_404, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from main.forms import StudentFrom, SubjectForm


class StudentListView(ListView):
    model = Student
    template_name = 'main/student_list.html'


def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f'{name} ({email}): {message}')

    context = {
        'title': 'Контакты'
    }
    return render(request, 'main/contact.html', context)


class StudentDetailView(DetailView):
    model = Student


class StudentCreateView(CreateView):
    model = Student
    form_class = StudentFrom
    success_url = reverse_lazy('main:index')


'''class StudentCreateView(CreateView):
    model = Student
    fields = ('first_name', 'last_name', 'avatar')
    success_url = reverse_lazy('main:index')
'''

# урок по формам
'''class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentFrom
    success_url = reverse_lazy('main:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Student, Subject, form='SubjectFrom', extra=1)
        context_data['formset'] = SubjectFormset()
        return context_data
'''


class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentFrom
    success_url = reverse_lazy('main:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        SubjectFormset = inlineformset_factory(Student, Subject, form=SubjectForm, extra=1)
        if self.request.method == 'POST':

            context_data['formset'] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = SubjectFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


'''class StudentUpdateView(UpdateView):
    model = Student
    fields = ('first_name', 'last_name', 'avatar')
    success_url = reverse_lazy('main:index')
'''


class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('main:index')


def toggle_activity(request, pk):
    student_item = get_object_or_404(Student, pk=pk)
    if student_item.is_active:
        student_item.is_active = False

    else:
        student_item.is_active = True

    student_item.save()

    return redirect(reverse('main:index'))

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">

                </div>
              {% include 'main/includes/inc_main_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Album</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
            <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator,
                etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
            <p>
                <a href="#" class="btn btn-primary my-2">Main call to action</a>
                <a href="#" class="btn btn-secondary my-2">Secondary action</a>
            </p>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% block content %}
                {% endblock %}

            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>&copy;2023-{% now 'Y' %}</p>
        <p>New to Bootstrap? <a href="../../..">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>

<script src="{% static  'js/popper.min.js' %}"></script>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                Офис МСК<br>
                Офис СПБ
            </p>
        </div>


    </div>
</div>
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <form method="post">
                <h2>Напишите нам</h2>
                {% csrf_token %}

                <input class="form-control" mb-2 name="name"/>
                <input class="form-control" mb-2 name="email"/>
                <textarea class="form-control" mb-2 name="message"></textarea>
                <button type="submit" class="btn btn-primary form-control">Отправить</button>
            </form>
        </div>


    </div>
</div>
{% endblock %}

main/templates/main/student_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Удалить студента {{ object.first_name }} {{ object.last_name }}?</p>
                            <button type="submit" class="btn btn-success">Подтвердить</button>
                            <a href="{% url 'main:index' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/student_detail.html
{% extends 'main/base.html' %}
{% block content %}

<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            {{ object.first_name }}
            {{ object.last_name }}
            {{ object.avatar }}
            {% if object.is_active%}
            Учится
            {% else %}
            Не учится
            {% endif %}
        </div>
        <div class="col-6">
        <img src="/media/{{ object.avatar }}" width="200" />
    </div>
    </div>
</div>
{% endblock %}

main/templates/main/student_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Студент
                        </h3>
                    </div>
                    <div class="card-body">


                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>

                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Предметы студента
                        </h3>
                    </div>
                    <div class="card-body">

                    {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                            <hr>
                            {% endif %}
                        {% endfor %}


                    </div>
                    <div class="card-footer"></div>
                </div>

            </div>

        </form>
    </div>
{% endblock %}

main/templates/main/student_list.html
{% extends 'main/base.html' %}
{% block content %}
    <a class="btn btn-outline-primary" href="{% url 'main:create_student' %}">Добавть студента</a>
{% for object in object_list %}
<div class="col-md-4">

    <div class="card mb-4 box-shadow">

        <div class="card-body">
            <p class="card-text">
                {% if object.is_active %}
                    {{ object|title }}</p>
                {% else %}
                    <span class="text-muted">{{ object| title }}</span>
                {% endif %}

            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'main:view_student' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Подробнее</a>
                    <a href="{% url 'main:update_student' object.pk %}" type="button" class="btn btn-sm btn-outline-secondary">Правка</a>
                    <a href="{% url 'main:delete_student' object.pk %}" type="button" class="btn btn-sm bg-danger">Удалить</a>

                </div>
                <div>
                    {% if object.is_active %}
                    <a href="{% url 'main:toggle_activity' object.pk %}" type="button" class="btn btn-sm btn-warning">Деактивировать</a>
                    {% else %}
                    <a href="{% url 'main:toggle_activity' object.pk %}" type="button" class="btn btn-sm btn-success">Активировать</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}