blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogCreatView, BlogDetailView, BlogUpdateView, BlogDeleteView, published_func, \
    FullListView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='start_list'),
    path('create/', BlogCreatView.as_view(), name='create'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('full_list/', FullListView.as_view(), name='full_list'),
    path('publishing/<int:pk>', published_func, name='published_func')
]

catalog/urls.py
from django.urls import path

from catalog.views import ContactView, HomeView

app_name = 'catalog'

urlpatterns = [
    path('contacts/', ContactView.as_view(), name='catalog'),
    path('', HomeView.as_view(), name='home'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# from catalog.views import catalog, home

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('home/', include('catalog.urls')),
                  path('', include('catalog.urls')),
                  path('login/', include('users.urls')),
                  path('dogs/', include('dogs.urls', namespace='dogs')),
                  path('lesson20_2/', include('lesson_20_2.urls')),
                  path('main/', include('main.urls', namespace='main')),
                  path('materials/', include('materials.urls', namespace='materials')),
                  path('blog/', include('blog.urls', namespace='blog'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path

from dogs.apps import DogsConfig
from dogs.views import   Breeds, DogsListView, DogCreateView, DogUpdateView, DogDeleteView, IndexView
#index,

app_name = DogsConfig.name

urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('breeds/', Breeds.as_view(), name='breeds'),
    path('<int:pk>/dogs/', DogsListView.as_view(), name='dogs_list'),
    path('create/', DogCreateView.as_view(), name='dog_create'),
    path('<int:pk>/edit/', DogUpdateView.as_view(), name='dog_update'),
    path('<int:pk>/delete/', DogDeleteView.as_view(), name='dog_delete')

]

materials/urls.py
from django.urls import path

from materials.views import MaterialCreateView, MaterialListView, MaterialDetailView, MaterialUpdateView, \
    MaterialDeleteView
from materials.apps import MaterialsConfig

app_name = MaterialsConfig.name

urlpatterns = [

    path('create/', MaterialCreateView.as_view(), name='create'),
    path('', MaterialListView.as_view(), name='list'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', MaterialUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MaterialDeleteView.as_view(), name='delete'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, ProfileView

app_name = 'users'


urlpatterns =[
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile')

]

catalog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.CharField(max_length=300, verbose_name="Описание", **NULLABLE)

    # create_at = models.DateField(verbose_name='date_at', **NULLABLE)
    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.CharField(max_length=100, verbose_name='Описание')
    image = models.ImageField(upload_to='photo/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="категория")
    price = models.FloatField(verbose_name='Цена')
    date_of_create = models.DateTimeField(verbose_name='Дата создания', **NULLABLE)
    date_of_last_change = models.DateField(verbose_name='Дата последнего изменения', **NULLABLE)

    def __str__(self):
        return self.name

catalog/views.py
from django.shortcuts import render
from catalog.models import Product
from django.shortcuts import render, reverse

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse_lazy


#def catalog(request):
#    return render(request, 'catalog/contacts.html')


class ContactView(TemplateView):
    template_name = 'catalog/contacts.html'
    extra_context = {"title": 'Контакты'}


class HomeView(ListView):
    model = Product
    template_name = 'catalog/index.html'

"""def home(request):
    product_list = Product.objects.all()
    context = {
        "object_list": product_list,
        "title": 'Товары'
    }

    return render(request, 'catalog/index.html', context)
"""

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>

    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "main:index" %}">Студенты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "dogs:index" %}">Питомник</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "materials:list" %}">Материалы</a>

        <a class="p-2 btn btn-outline-primary" href="{% url "blog:start_list" %}">Блог</a>

        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url "users:logout" %}">Выйти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "users:profile" %}">Профиль</a>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url "users:login" %}">Войти</a>
        <a class="p-2 btn btn-outline-primary" href="{% url "users:register" %}">Регистрация</a>
        {% endif %}


    </nav>

</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
{% block content_2 %}
{% endblock %}




    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
Footer
© 2023 GitHub, Inc. 

catalog/templates/catalog/home.html
{% load newtags %}

<div class="container">
    <div class="row text-center">

            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">

                        <h4 class="my-0 font-weight-normal">{{ object.name|title }}</h4>
                    </div>
                    <div>
                    <img src="{% mediapath object.image %}"  width="100" height="111" alt="Нет картинки">
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ object.price }}</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li></li>
                            <li>{{ object.description }}</li>
                            <li>{{ object.date_of_create}}</li>
                            <li>{{ object.date_of_last_change}}</li>

                        </ul>
                        <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                    </div>

                 </div>
            </div>
    </div>
</div>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% block content_2 %}

    <div class="row">
        {% for object in object_list %}
            {% include 'catalog/home.html' with object=object%}
        {% endfor %}
    </div>
{% endblock %}